from app.models.consultorio import Consultorio
from app.models.usuario import Usuario
from app.models.paciente import Paciente
from app.models.odontologo import Odontologo
from app.models.turno import Turno
from app.models.historia_clinica import HistoriaClinica
from app.models.tratamiento_catalogo import TratamientoCatalogo
from app.models.tratamiento_realizado import TratamientoRealizado
from app.models.odontograma import Odontograma
from app.models.pago import Pago